### ISSUE TITLE
Формат отображения

### ISSUE THREAD

**Issue by Mr-Coquin** [forest-lynx/moonshine-decimal-field#5]
Есть поле 
   $table->decimal('sum', 8, 2)->nullable();
   
   Вывожу в moonshine:
Decimal::make('Sum', 'sum'),

Значение выводит сразу по умолчанию : "0.00", не пустое. При фокусе поля, оно не очищается, приходиться через "backspace" удалять 
Так же если мы вводим значение скажем "324,342,342,343.43" хотелось бы иметь возможность вывода в виде "324 342 342 343.43"

**Comment by forest-lynx** [comment]
Добрый день!
Спасибо за обратную связь. По нулевому значению при фокусе на днях посмотрю. Форматирование поля происходит на основе [NumberFormatter](https://www.php.net/manual/ru/class.numberformatter.php) исходя из установленной локали, по умолчанию сведения о локали берутся из настроек приложения, у поля имеется метод [locale()](https://github.com/forest-lynx/moonshine-decimal-field#методы) для ее переопределения.

**Comment by Mr-Coquin** [comment]
> Добрый день! Спасибо за обратную связь. По нулевому значению при фокусе на днях посмотрю. Форматирование поля происходит на основе [NumberFormatter](https://www.php.net/manual/ru/class.numberformatter.php) исходя из установленной локали, по умолчанию сведения о локали берутся из настроек приложения, у поля имеется метод [locale()](https://github.com/forest-lynx/moonshine-decimal-field#%D0%BC%D0%B5%D1%82%D0%BE%D0%B4%D1%8B) для ее переопределения.

Добрый . Да с locale помогло выставлением на "ru". Спасибо я пытался до этого передовая "en". Тогда остается дождаться значения что бы было пустое или же 0.00 выставлялись в "placeholder" как подсказка а не сразу в value

**Comment by Mr-Coquin** [comment]
И по сохранению. Нужно ли в модели что то прописывать ?
Decimal::make('Sum', 'sum')
->locale('ru'),
 Я всегда получаю. В таблицы уже со всеми разными типами пытался работать поля
Cannot access offset of type string on string (ошибка понимаю почему такая, нов доке ничего нет)
Но стоит изменить на
Text::make('Sum', 'sum') начинает сохранять

**Comment by forest-lynx** [comment]
Добрый день!
Какой тип поля в базе данных? Имеются ли касты в модели у данного поля?

**Comment by forest-lynx** [comment]
> И по сохранению. Нужно ли в модели что то прописывать ? Decimal::make('Sum', 'sum') ->locale('ru'), Я всегда получаю. В таблицы уже со всеми разными типами пытался работать поля Cannot access offset of type string on string (ошибка понимаю почему такая, нов доке ничего нет) Но стоит изменить на Text::make('Sum', 'sum') начинает сохранять

Добрый день! К сожалению не смог у себя воспроизвести Вашу проблему. Прошу создать новый "Issues" с подробным описанием Ваших действий при которых Вы получаете данную ошибку.
