### ISSUE TITLE
Ошибка "Cannot access offset of type string on string"

### ISSUE THREAD

**Issue by Mr-Coquin** [forest-lynx/moonshine-decimal-field#7]
Ошибка "Cannot access offset of type string on string"

1) Файл миграции создает поле  (варианты разные пробивал, какой тип вы указываете и кодировку ?)
$table->string('sum')->default(0)->nullable();

2)В модели кастов никаких нет

3)В  protected $fillable  поле указано 

4)На FormPage подключаю use ForestLynx\MoonShine\Fields\Decimal;

5)В  public function fields(): array
 Decimal::make('Sum', 'sum')->locale('ru')->precision(2), 
 так же пребывал варианты 
  Decimal::make('Sum', 'sum')->precision(2), 
и
  Decimal::make('Sum', 'sum')
  
  так же если оставить поле пустым и попытаться сохранить его получаю другую ошибку 
  
  Trying to access array offset on value of type bool

**Comment by forest-lynx** [comment]
Добрый день!
На днях проверю Ваш кейс, перед вставкой данных в базу происходит преобразование значения через NumberFormatter на выходе имеем int|float|false(если не удалось распарсить входные данные). 
Прошу подскажите какую базу данных вы используете?

**Comment by forest-lynx** [comment]
Огромное Вам спасибо за обратную связь и выявление проблем с пакетом. В настоящее время все ошибки устранил. Единственное при работе с строковыми представлениями значений в базе данных необходимо их соответствие указанной локали для поля. Поставил себе на заметку проработать вопрос по обработке строковых представлений более углубленно. Я просто привык хранить данные в базе в виде int и затем их трансформировать в нужный формат.

**Comment by Mr-Coquin** [comment]
Подтверждаю, работает теперь :)
